version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: app_produtos_back
    restart: always
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: app_frontend_front
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3009:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
